language: scala

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage test
  - sbt ++$TRAVIS_SCALA_VERSION coverageReport
  - sbt ++$TRAVIS_SCALA_VERSION coverageAggregate
  - sbt ++$TRAVIS_SCALA_VERSION codacyCoverage

after_success:
  - pip install --user codecov && codecov
